version: '3.9'
name: tp1
services:

  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: Dockerfile
    ports:
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 50s
    networks:
      - rabbit_net
    logging:
      driver: "none"

  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONHASHSEED=0
      - LOGGING_LEVEL=INFO
      - CANT_FILTROS_ESCALAS=1
      - CANT_FILTROS_DISTANCIA=1
      - CANT_FILTROS_VELOCIDAD=1
      - CANT_FILTROS_PRECIO=1
      - CANT_WATCHDOGS=1
    depends_on:
      - filtro_escalas1
      - filtro_distancia1
      - filtro_velocidad1
      - filtro_precio1

    networks:
      - testing_net
      - rabbit_net
    volumes:
      - type: bind
        source: ./server/config.ini
        target: /config.ini
      - type: bind
        source: ./data/server
        target: /data

  filtro_escalas1:
    container_name: filtro_escalas1
    image: filtro_escalas:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONHASHSEED=0
      - LOGGING_LEVEL=INFO
      - ID=1
      - CANT_FILTROS_VELOCIDAD=1
      - CANT_WATCHDOGS=1
    depends_on:
      rabbitmq:
         condition: service_healthy
    networks:
      - rabbit_net
    volumes:
      - type: bind
        source: ./filtros/filtro_escalas/config.ini
        target: /config.ini
      - type: bind
        source: ./data/filtro_escalas1
        target: /data
    
  filtro_distancia1:
    container_name: filtro_distancia1
    image: filtro_distancia:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONHASHSEED=0
      - LOGGING_LEVEL=INFO
      - ID=1
      - CANT_WATCHDOGS=1
    depends_on:
      rabbitmq:
         condition: service_healthy
    networks:
      - rabbit_net
    volumes:
      - type: bind
        source: ./filtros/filtro_distancia/config.ini
        target: /config.ini
      - type: bind
        source: ./data/filtro_distancia1
        target: /data
        

    
  filtro_velocidad1:
    container_name: filtro_velocidad1
    image: filtro_velocidad:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONHASHSEED=0
      - LOGGING_LEVEL=INFO
      - ID=1
      - CANT_FILTROS_ESCALAS=1
      - CANT_WATCHDOGS=1
    depends_on:
      - calculador_promedio
    networks:
      - rabbit_net
    volumes:
      - type: bind
        source: ./filtros/filtro_velocidad/config.ini
        target: /config.ini
      - type: bind
        source: ./data/filtro_velocidad1
        target: /data
    
  filtro_precio1:
    container_name: filtro_precio1
    image: filtro_precio:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONHASHSEED=0
      - LOGGING_LEVEL=INFO
      - ID=1
      - CANT_WATCHDOGS=1
    depends_on:
      rabbitmq:
         condition: service_healthy
    networks:
      - rabbit_net
    volumes:
      - type: bind
        source: ./filtros/filtro_precio/config.ini
        target: /config.ini
      - type: bind
        source: ./data/filtro_precio1
        target: /data
    
  calculador_promedio:
    container_name: calculador_promedio
    image: calculador_promedio:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONHASHSEED=0
      - LOGGING_LEVEL=INFO      
      - CANT_FILTROS_PRECIO=1
      - CANT_WATCHDOGS=1
    depends_on:
      rabbitmq:
         condition: service_healthy
    networks:
      - rabbit_net
    volumes:
      - type: bind
        source: ./filtros/calculador_promedio/config.ini
        target: /config.ini
      - type: bind
        source: ./data/calculador_promedio
        target: /data

  client:
    container_name: client
    image: client:latest
    entrypoint: python3 /main.py 
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONHASHSEED=0
      - LOGGING_LEVEL=INFO
    networks:
      - testing_net
    depends_on:
      - server
    volumes:
      - type: bind
        source: ./client/config.ini
        target: /config.ini
      - type: bind
        source: ./data/client
        target: /data
      - type: bind
        source: ./data/client
        target: /resultados

  watchdog1:
    container_name: watchdog1
    image: watchdog:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONHASHSEED=0
      - LOGGING_LEVEL=INFO      
      - CANT_FILTROS_ESCALAS=1
      - CANT_FILTROS_DISTANCIA=1
      - CANT_FILTROS_VELOCIDAD=1
      - CANT_FILTROS_PRECIO=1
      - CANT_WATCHDOGS=1
      - ID=1
    depends_on:
      rabbitmq:
         condition: service_healthy
    networks:
      - rabbit_net
    volumes:
      - type: bind
        source: ./watchdog/config.ini
        target: /config.ini
      - /var/run/docker.sock:/var/run/docker.sock

  clientes_prueba1:
    container_name: clientes_prueba1
    image: client:latest
    entrypoint: python3 /main.py 
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONHASHSEED=0
      - LOGGING_LEVEL=INFO
    networks:
      - testing_net
    depends_on:
      - server    
    volumes:
      - type: bind
        source: ./data/client1/config.ini
        target: /config.ini
      - type: bind
        source: ./data/client
        target: /data
      - type: bind
        source: ./data/client1
        target: /resultados

  clientes_prueba2:
    container_name: clientes_prueba2
    image: client:latest
    entrypoint: python3 /main.py 
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONHASHSEED=0
      - LOGGING_LEVEL=INFO
    networks:
      - testing_net
    depends_on:
      - server    
    volumes:
      - type: bind
        source: ./data/client2/config.ini
        target: /config.ini
      - type: bind
        source: ./data/client
        target: /data
      - type: bind
        source: ./data/client2
        target: /resultados

  clientes_prueba3:
    container_name: clientes_prueba3
    image: client:latest
    entrypoint: python3 /main.py 
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONHASHSEED=0
      - LOGGING_LEVEL=INFO
    networks:
      - testing_net
    depends_on:
      - server    
    volumes:
      - type: bind
        source: ./data/client3/config.ini
        target: /config.ini
      - type: bind
        source: ./data/client
        target: /data
      - type: bind
        source: ./data/client3
        target: /resultados

  clientes_prueba4:
    container_name: clientes_prueba4
    image: client:latest
    entrypoint: python3 /main.py 
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONHASHSEED=0
      - LOGGING_LEVEL=INFO
    networks:
      - testing_net
    depends_on:
      - server    
    volumes:
      - type: bind
        source: ./data/client4/config.ini
        target: /config.ini
      - type: bind
        source: ./data/client
        target: /data
      - type: bind
        source: ./data/client4
        target: /resultados

  clientes_prueba5:
    container_name: clientes_prueba5
    image: client:latest
    entrypoint: python3 /main.py 
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONHASHSEED=0
      - LOGGING_LEVEL=INFO
    networks:
      - testing_net
    depends_on:
      - server    
    volumes:
      - type: bind
        source: ./data/client5/config.ini
        target: /config.ini
      - type: bind
        source: ./data/client
        target: /data
      - type: bind
        source: ./data/client5
        target: /resultados

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 168.25.125.0/24
  rabbit_net:
    ipam:
      driver: default
      config:
        - subnet: 128.25.125.0/24
